version: "3.8"

services:
  blue:
    build: ./app_blue
    container_name: blue_app
    networks:
      - app_net

  green:
    build: ./app_green
    container_name: green_app
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green
    networks:
      - app_net

networks:
  app_net:
